site_name: arxiv2025_expert_eval_rw
nav:
  - Home: index.md

theme:
  name: material

plugins:
  - search
  - mkdocstrings:
      project_name: arxiv2025_expert_eval_rw
      handlers:
        python:
          options:
            docstring_style: numpy